#!/usr/bin/env python3
import rospy
from geometry_msgs.msg import Twist
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
import cv2

class GiraYCaptura:
    def __init__(self):

        #indicializar nodo
        rospy.init_node('node_capture')

        #publicador
        self.pub = rospy.Publisher('/cmd_vel', Twist, queue_size=1)

        #suscriptor
        self.sub = rospy.Subscriber('/camera/rgb/image_raw', Image, self.image_callback)
        self.bridge = CvBridge()

        self.rate = rospy.Rate(10)
        self.girar()

    def girar(self):
        twist = Twist()
        twist.angular.z = 0.3  # Gira sobre su eje

        while not rospy.is_shutdown():
            self.pub.publish(twist)
            self.rate.sleep()
            

    def image_callback(self, msg):
        img = self.bridge.imgmsg_to_cv2(msg, desired_encoding='bgr8')
        cv2.imshow("Camara TurtleBot3", img)
        cv2.waitKey(1)

if __name__ == '__main__':
    try:
        GiraYCaptura()
    except rospy.ROSInterruptException:
        pass
    finally:
        cv2.destroyAllWindows()